@baseUrl = http://localhost:5000

### Health Check
GET {{baseUrl}}/health

### Analyze: Lanugae Validation
POST {{baseUrl}}/test-validator
Content-Type: application/json

{
  "code": "arr = [1,2,3] \nfor i in arr: for j in arr: if i<j: arr[i], arr[j] = arr[j], arr[i]",
  "language": "python"int(i) 
}

### Analyze: Model Response
POST {{baseUrl}}/analyze
Content-Type: application/json

{
  "code": "def foo(\n    print('broken'",
  "language": "python"
}

### Analyze:Brute force 
POST {{baseUrl}}/analyze
Content-Type: application/json

{
  "code": "def find_pairs(arr, target):\n    n = len(arr)\n    result = []\n    for i in range(n):\n        for j in range(i + 1, n):\n            if arr[i] + arr[j] == target:\n                result.append((arr[i], arr[j]))\n    return result",
  "language": "python"
}

### Analyze:Brute force 
POST {{baseUrl}}/analyze
Content-Type: application/json

{
  "code": "def find_pairs(arr, target):\n    n = len(arr)\n    result = []\n    for i in range(n):\n        for j in range(i + 1, n):\n            if arr[i] + arr[j] == target:\n                result.append((arr[i], arr[j]))\n    return result",
  "language": "python"
}
### Error Validation
GET http://127.0.0.1:5000/analyze