@baseUrl = http://localhost:5000

### Health Check
GET {{baseUrl}}/health

### Analyze: Lanugae Validation
POST {{baseUrl}}/test-validator
Content-Type: application/json

{
  "code": "for i in range(n): for j in range(n): print(i+j)",
  "language": "python"
}



